### ISSUE TITLE
Canvas Editor Crash

### ISSUE THREAD

**Issue by WenXin20** [Fureniku/Graffiti#1]
`Minecraft v1.15.2`
`Forge v31.2.5`
`Graffiti v1.2.0`

I got this crash by right-clicking the Canvas Editor on a blank graffiti. 
I was on my server and my client crashed, if that makes a difference.
[Crash Report](https://gist.github.com/WenXin20/5410a056ea9ae34b4aff168b331d06b0)

**Comment by Fureniku** [comment]
Fixed in 1.2.1
